//
//  AddTaskModels.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 06/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddTask
{
    // MARK: Use cases
    
    enum Save {
        struct Request {
            var title: String
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum Fetch {
        struct Request {
        }
        struct Response {
            var activity: ActivityEntity
            var items: [TaskEntity]
        }
        struct ViewModel {
            struct ItemViewModel {
                var index: String
                var title: NSAttributedString
                var isChecked: Bool
            }
            var title: String
            var checkList: String
            var items: [ItemViewModel]
        }
    }
    
    enum Checked {
        struct Request {
            var index: Int
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
