//
//  AddActivitiesPresenter.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 04/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddActivitiesPresentationLogic {
    func presentAlert(response: AddActivities.Add.Response)
    func presentMembers(response: AddActivities.Member.Response)
}

class AddActivitiesPresenter: AddActivitiesPresentationLogic {
    weak var viewController: AddActivitiesDisplayLogic?
    
    // MARK: Do Add
    
    func presentAlert(response: AddActivities.Add.Response) {
        let viewModel = AddActivities.Add.ViewModel(success: response.success,
                                                    message: response.message)
        viewController?.displayAlert(viewModel: viewModel)
    }
    
    func presentMembers(response: AddActivities.Member.Response) {
        let memberViewModel = getMembersViewModel(response: response)
        let viewModel = AddActivities.Member.ViewModel(members: memberViewModel)
        viewController?.displayMembers(viewModel: viewModel)
    }
    
    private func getMembersViewModel(response: AddActivities.Member.Response) -> [AddActivities.Member.ViewModel.MemberViewModel] {
        var members: [AddActivities.Member.ViewModel.MemberViewModel] = []
        for element in response.members {
            members += [AddActivities.Member.ViewModel.MemberViewModel(title: element.title,
                                                                       photo: element.photo,
                                                                       isLast: false)]
        }
        members += [AddActivities.Member.ViewModel.MemberViewModel(title: "Add Member",
                                                                   photo: UIImage(named: "Add-User-Placeholder") ?? UIImage(),
                                                                   isLast: true)]
        return members
    }
}
