//
//  AddActivitiesWorker.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 04/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class AddActivitiesWorker {

    func saveActivity(request: AddActivities.Add.Request, members: [AddActivities.Member.Response.MemberResponse],  handler: @escaping () -> Void) {
        if let context = CoreDataManager.shared.mainContext {
            let activity = NSEntityDescription.insertNewObject(forEntityName: "ActivityEntity", into: context) as! ActivityEntity
            activity.title = request.title
            activity.desc = request.description
            activity.dueDate = request.dueDate! as NSDate
            if let aImage = request.image {
                activity.image = aImage.jpegData(compressionQuality: 0.6)! as NSData
            }
            for element in members {
                let member = NSEntityDescription.insertNewObject(forEntityName: "MemberEntity", into: context) as! MemberEntity
                member.name = element.title
                member.photo = element.photo.jpegData(compressionQuality: 0.6)! as NSData
                member.activity = activity
                activity.addToMember(member)
            }
            CoreDataManager.shared.saveMainContext()
            handler()
        }
    }
}
