//
//  ActivitiesRouter.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 03/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ActivitiesRoutingLogic {
    func routeToAddTask(at index: Int)
}

protocol ActivitiesDataPassing {
    var dataStore: ActivitiesDataStore? { get }
}

class ActivitiesRouter: NSObject, ActivitiesRoutingLogic, ActivitiesDataPassing {
    weak var viewController: ActivitiesViewController?
    var dataStore: ActivitiesDataStore?
    
    // MARK: Routing
    
    func routeToAddTask(at index: Int) {
        let vc = viewController?.storyboard?.instantiateViewController(withIdentifier: "AddTaskViewController") as! AddTaskViewController
        var destinationDS = vc.router!.dataStore!
        passDataToVC(at: index, source: dataStore!, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    //MARK: Passing data
    
    func passDataToVC(at index: Int, source: ActivitiesDataStore, destination: inout AddTaskDataStore) {
        destination.activity = source.activity[index]
    }
}
