//
//  ActivitiesPresenter.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 03/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ActivitiesPresentationLogic {
    func presentSomething(response: Activities.Something.Response)
}

class ActivitiesPresenter: ActivitiesPresentationLogic {
    weak var viewController: ActivitiesDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Activities.Something.Response) {
        let viewModel = Activities.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
