//
//  AddMembersRouter.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 05/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddMembersRoutingLogic {
    func routeToBack()
}

protocol AddMembersDataPassing {
    var dataStore: AddMembersDataStore? { get }
}

class AddMembersRouter: NSObject, AddMembersRoutingLogic, AddMembersDataPassing {
    weak var viewController: AddMembersViewController?
    var dataStore: AddMembersDataStore?
    
    // MARK: Routing
    
    func routeToBack() {
        viewController?.completionHandler(dataStore!.member)
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: AddMembersViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: AddMembersDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
