//
//  AddMembersInteractor.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 05/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddMembersBusinessLogic {
    func fetch(request: AddMembers.Fetch.Request)
    func doSomething(request: AddMembers.Something.Request)
}

protocol AddMembersDataStore {
    var member: AddActivities.Member.Response.MemberResponse? { get set }
}

class AddMembersInteractor: AddMembersBusinessLogic, AddMembersDataStore {
    
    var presenter: AddMembersPresentationLogic?
    var worker: AddMembersWorker?
    var member: AddActivities.Member.Response.MemberResponse?
    
    // MARK: Do something
    func fetch(request: AddMembers.Fetch.Request) {
        guard let aMember = member else {
            return
        }
        let response = AddMembers.Fetch.Response(title: aMember.title,
                                                 photo: aMember.photo)
        presenter?.present(response: response)
    }
    
    func doSomething(request: AddMembers.Something.Request) {
        let validation = validateForm(request: request)
        if validation.isValid {
            member = AddActivities.Member.Response.MemberResponse(title: request.title,
                                                                  photo: request.image!)
        }
        let response = AddMembers.Something.Response(success: validation.isValid,
                                                     message: validation.message)
        presenter?.presentSomething(response: response)
    }
    
    private func validateForm(request: AddMembers.Something.Request) -> (isValid: Bool, message: String) {
        var isValid = false
        var msg = ""
        if request.title == "" {
            msg = "Please enter name"
        } else if request.image == nil || request.image == UIImage(named: "User-Placeholder") {
            msg = "Please choose a profile image"
        } else {
            isValid = true
            msg = "Member added!"
        }
        return (isValid, msg)
    }
}
