//
//  AddMembersModels.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 05/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddMembers {
    // MARK: Use cases
    enum Fetch {
        struct Request {
        }
        struct Response {
            var title: String
            var photo: UIImage
        }
        struct ViewModel {
            var title: String
            var photo: UIImage
        }
    }
    
    enum Something {
        struct Request {
            var title: String
            var description: String
            var image: UIImage?
        }
        struct Response {
            var success: Bool
            var message: String
        }
        struct ViewModel {
            var success: Bool
            var message: String
        }
    }
}
