//
//  AddMembersPresenter.swift
//  ActivityTracker
//
//  Created by Antony Raphel on 05/12/18.
//  Copyright (c) 2018 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddMembersPresentationLogic {
    func present(response: AddMembers.Fetch.Response)
    func presentSomething(response: AddMembers.Something.Response)
}

class AddMembersPresenter: AddMembersPresentationLogic {
    weak var viewController: AddMembersDisplayLogic?
    
    // MARK: Do something
    
    func present(response: AddMembers.Fetch.Response) {
        let viewModel = AddMembers.Fetch.ViewModel(title: response.title,
                                                   photo: response.photo)
        viewController?.display(viewModel: viewModel)
    }
    
    func presentSomething(response: AddMembers.Something.Response) {
        let viewModel = AddMembers.Something.ViewModel(success: response.success,
                                                       message: response.message)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
